### ISSUE TITLE
Fails with SELinux

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/sdbootutil#10]
snapper.log has

```
stderr: logger: socket /dev/log: Permission denied
```

Apparently it's not necessary to use logger in that context as snapper already deals with logging?

**Comment by TobiPeterG** [comment]
I see two solutions here, we can either remove the logging line or make it conditional so the script doesn't fail when logging isn't possible:
`logger -t snapper "$0 $@" || echo "Script logging is not possible, skipping..."`
(or some other message, if it should be indicated at all)

**Comment by lnussel** [comment]
is only for debugging anyway, could just remove it

**Comment by TobiPeterG** [comment]
seems to be fixed already
