### ISSUE TITLE
Wrong check for transactional-update

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/sdbootutil#11]
https://github.com/lnussel/sdbootutil/blob/a0e666f3d0a6ec524f26b7c30d0ff1ee02b9e96e/10-sdbootutil.snapper#L6-L11

`/etc` is an `overlayfs` both outside and inside the transaction.

To distinguish that, check for `$TRANSACTIONAL_UPDATE`. Or if you want to detect chroots, `[ -w /run/systemd ]`

**Comment by lnussel** [comment]
the use of this function does not care whether called inside or outside?

**Comment by Vogtinator** [comment]
Yes, but it's meant to detect whether it's inside:

```
# don't handle this here if called within transactional-update.
```

but it also returns true if it's outside of transactional-update.

Either the code is wrong or the comment.
