### ISSUE TITLE
[bug?] update-predictions fails on previously enrolled systems

### ISSUE THREAD

**Issue by TobiPeterG** [openSUSE/sdbootutil#118]
On two seperate machines, I had a TPM policy enrolled for my system drive. After a recent update, sdbootutil wasn't able anymore to update the predictions, this is the log:
https://pastebin.com/FZpMBmgK

When I added the options --ask-pin, it asked for the PIN, I entered the password of my drive and I got the message that the PIN is wrong or the TPM has locked after two many failed attempts. I tried to clear the TPM in my UEFI, but that didn't fix it, re-enrolling the policy also didn't work.

I managed to fix it thanks to an Aeon user, they seem to have the same problem:
https://bugzilla.suse.com/show_bug.cgi?id=1228863

After
`echo 5 | sudo tee /sys/class/tpm/tpm0/ppi/request`
reboot
`tpm2_dictionarylockout -Tdevice:/dev/tpmrm0 --setup-parameters --max-tries=5 --clear-lockout`
re-enroll using systemd-cryptsetup
reboot
It didn't unlock the drive, so I deleted the `/var/lib/systemd/pcrlock.json` file and re-ran
`sdbootutil -vv update-predictions`

This then gave this output:
https://pastebin.com/dveXK67L

It created a new file in
`/boot/efi/loader/credentials/pcrlock.opensuse-tumbleweed.cred`
and created a new `/var/lib/systemd/pcrlock.json`

However, the TPM still doesn't unlock the drive after reboot, I don't know why.

At least, sdbootutil can update the predictions again, I don't know what step exactly fixed it, will investigate further on my second machine.
I'm also not sure if this is something sdbootutil can fix, but it is not very nice that **something** just broke prediction enrollment that previously worked. My guess is that with systemd 256 something changed that made it incompatable with the previous enrollments.

This seems to be related to
https://github.com/systemd/systemd/issues/28655

**Comment by aplanas** [comment]
> On two seperate machines, I had a TPM policy enrolled for my system drive.

This is real hardware, not VMs, right?

> After a recent update, sdbootutil wasn't able anymore to update the predictions, this is the log

You can see the wrong predicted PCRs checking `/usr/lib/systemd/systemd-pcrlock` table.  This shows the event log associated with the pcrlock file.  You can see if there is a missing association.  If you can boot on the old system, you can also pipe the output to a file and do a diff -u to understand what is different now.

> When I added the options --ask-pin, it asked for the PIN, I entered the password of my drive and I got the message that the PIN is wrong or the TPM has locked after two many failed attempts. I tried to clear the TPM in my UEFI, but that didn't fix it, re-enrolling the policy also didn't work.

Try the new commands `unenroll` and `enroll`

We should be debugging why the PIN is not valid.

> 
> I managed to fix it thanks to an Aeon user, they seem to have the same problem: https://bugzilla.suse.com/show_bug.cgi?id=1228863
> 
> After `echo 5 | sudo tee /sys/class/tpm/tpm0/ppi/request` reboot `tpm2_dictionarylockout -Tdevice:/dev/tpmrm0 --setup-parameters --max-tries=5 --clear-lockout` re-enroll using systemd-cryptsetup reboot It didn't unlock the drive, so I deleted the `/var/lib/systemd/pcrlock.json` file and re-ran `sdbootutil -vv update-predictions`
> 
> This then gave this output: https://pastebin.com/dveXK67L
> 
> It created a new file in `/boot/efi/loader/credentials/pcrlock.opensuse-tumbleweed.cred` and created a new `/var/lib/systemd/pcrlock.json`
> 
> However, the TPM still doesn't unlock the drive after reboot, I don't know why.

You need to enroll the devices. As pointed before: use the `unenroll` and `enroll` commands. Those would enroll the devices

**Comment by TobiPeterG** [comment]
Ah nevermind, following this guide for a lost PIN fixed it for me :)
https://en.opensuse.org/Portal:MicroOS/FDE#Re-enrollment

Now working on both systems as expected again :)

**Comment by francoism90** [comment]
@TobiPeterG I also have this issue: Failed to write to NV index: State not recoverable

Can you remember exactly what you did? Did you also enabled/disabled BIOS related settings?

Thanks

**Comment by TobiPeterG** [comment]
> @TobiPeterG I also have this issue: Failed to write to NV index: State not recoverable
> 
> Can you remember exactly what you did? Did you also enabled/disabled BIOS related settings?
> 
> Thanks

No.
Check the encrypted devices sdbootutil tracks with sdbootutil list-devices
Then, sdbootutil unenroll
And
Sdbootutil enroll
Afterwards it will work again :)

**Comment by aplanas** [comment]
We should try to avoid `sdbootutil unenroll; sdbootutil enroll`.

If you remember the recovery PIN (is the same that the recovery key if you never unenrolled the system), you can do `sdbootutil --ask-pin update-predictions`.

If the recovery PIN is lost, yeah, you need to re-enroll the system, but in this case do `sdbootuil unenroll; sdbootutil --ask-pin enroll` and enter some password that you can use later

**Comment by francoism90** [comment]
@aplanas Thanks!

I completely removed all enrolled keys, and did enroll them again. Now it works. :)
