### ISSUE TITLE
Error: Bootloader not detected (openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by DiamivaeBro** [openSUSE/sdbootutil#140]
After recent update sdbootutil started giving me "Error: Bootloader not detected
" error for every action ive tried

Most interesting 
Bootctl giving me valid result,sdboot installed and perfectly working

**Comment by DiamivaeBro** [comment]
How i can see in line 1403 sdbootutil cheking sdboot in /usr/lib/systemd-boot , but sdboot in opensuse uses /usr/lib/systemd-boot/boot path now

I think thats causes problem

Just need to change few lines

**Comment by aplanas** [comment]
Check if you have the file `/etc/sysconfig/bootloader`, and if so change the `LOADER_TYPE="grub2-efi"` to `LOADER_TYPE="systemd-boot"`

**Comment by DiamivaeBro** [comment]
It helped
Thanks

**Comment by aplanas** [comment]
Thanks! I will add a better error message in `sdbootutil` for this case. To track this I will re-open the issue.
