### ISSUE TITLE
Arithmetic syntax error due to multiple output lines from findmnt

### ISSUE THREAD

**Issue by Samonitari** [openSUSE/sdbootutil#170]
```
grep: warning: stray \ before /
Cleaning /boot
/usr/bin/sdbootutil: line 747: 3852673024
3852673024 / 1024: syntax error in expression (error token is "3852673024 / 1024")
/usr/bin/sdbootutil: line 773: [: : integer expression expected
grep: warning: stray \ before /
Cleaning /boot
/usr/bin/sdbootutil: line 747: 3812921344
3812921344 / 1024: syntax error in expression (error token is "3812921344 / 1024")
/usr/bin/sdbootutil: line 773: [: : integer expression expected
```

After some trial and error this is caused by my system setup resulting in findmnt reporting twice
``` console
# findmnt -n -b -o AVAIL --target /boot
3773169664
3773169664
```
This is used here:
https://github.com/openSUSE/sdbootutil/blob/1370153ddc826909a8312255d8197d1589286059/sdbootutil#L747C12-L747C19

This is probably related to **not** having mount entry for /boot in my fstab, but relying on `systemd-gpt-auto-generator` generating `boot.automount` from recognizing the partition type UUID `c12a7328-f81f-11d2-ba4b-00a0c93ec93b`

I can open a PR to handle this

**Comment by aplanas** [comment]
Closed by #171
