### ISSUE TITLE
installed_by_sdbootutil file gets removed by bootctl cleanup

### ISSUE THREAD

**Issue by TobiPeterG** [openSUSE/sdbootutil#19]
The wiki recommends to use bootctl cleanup to remove dangling initrd files. However, it also removes the installed_by_sdbootutil file.
Can this be confirmed?

**Comment by lnussel** [comment]
yes. need to find a different way

**Comment by TobiPeterG** [comment]
> yes. need to find a different way

What is the reasoning behind placing it in exactly *that* location? Couldn't it be placed where the systemd bootloader EFI file is placed?

BTW.: In the wiki is stated that not always the correct boot entry is booted and to set it after boot manually.
However, in the boot menu, by pressing "d" with an entry selected, one can change the default boot entry, that might be easier. :)

**Comment by TobiPeterG** [comment]
This seems to have been fixed at some point
