### ISSUE TITLE
discussion: rethink out-of-space approach

### ISSUE THREAD

**Issue by TobiPeterG** [openSUSE/sdbootutil#26]
Currently, when there's not enough space on the ESP, the command exits with an error code. However, this might not always be obvious. This might lead to a system with no bootable entry for the current snapshot. The user then has to manually remove snapshots until old kernels got deleted and then recreate the entries to get a booting system with the current snapshot again.

Instead, one might choose a different approach to handling this issue:
If a kernel should be generated for the most recent/rw snapshot,
a) delete the oldest kernel(s) and its associated snapshots. The oldest kernel is probably used by the oldest snaphsots and therefore likely irrelevant
b) delete the kernel with the least number of associated snapshots. This way, the smallest possible number of snapshots are deleted

This way, the user autmatically has a booting system.

**Comment by lnussel** [comment]
yes, we could also just remove the boot entries for old snapshots without actually cleaning up the snapshots. There's likely more space for snapshots than for kernel/initrds in the ESP

**Comment by throttlemeister** [comment]
If you leave the snapshot, you can still recover files from it, but it is no longer bootable. I guess that is ok. What is more troublesome, is that snapper prunes old snapshots (good) but entries in the boot menu are not. It is therefor likely a lot more boot entries exist for non-existent snapshots than the other way around. See also my comment in the other issue.

**Comment by lnussel** [comment]
when removing snapshots, snapper is supposed to call the sdbootutil plugin and remove kernels and entries from the ESP first. Do you by chance have logs of a case where this didn't happen?

**Comment by lnussel** [comment]
The plugin is in `sdbootutil-snapper`, should be pulled in automatically. Snapper logs into /var/log/snapper.log

**Comment by throttlemeister** [comment]
I checked the logs. I can see sdbootutil-snapper cleans up snapshot entries like pre and post, but no other snapshots. So there are still plenty snapshot configs in the bootloader related to kernels that are no longer present on the system.

Example:
# snapper list shows 19 snapshot entries listed for root
 
# sdbootutil kernels show 6.6.10 and 6.6.11 installed

And finally an ls of /boot/efi/loader/entries shows 54 snapshot configs for the bootmenu, the oldest being for kernel 6.6.3

**Comment by lnussel** [comment]
Could have happened during development. The question whether it still happens today with current snapper and sdbootutil. That is unrelated to this ticket so I'd suggest to open a new one if you see new snapshots also causing stale files.

To clean up your esp manually you may want to try sdbootutil from https://github.com/lnussel/sdbootutil/tree/wip, eg. using `sdbootutil -v list-entries` that one will tell you about missing snapshots.

**Comment by TobiPeterG** [comment]
done in #99
