### ISSUE TITLE
Support for other file-systems than btrfs (ext4) on the roadmap?

### ISSUE THREAD

**Issue by tvogel** [openSUSE/sdbootutil#50]
I have been bitten with btrfs problems too often, so regardless of its convincing advantages like snapshots, I am still using the trustworthy ext4 on my root file systems. Obviously, sdbootutil does not work with that. Still, I would need its functionality to arrange the secure-boot shim accordingly and currently need to do that by hand.
Is extension to other file-systems (lacking subvolumes/snapshots) on the roadmap?

**Comment by lnussel** [comment]
not for sdbootutil so far. Without snapshots the standard upstream tooling might just work. perl-Bootloader has some basic systemd-boot support too.
