### ISSUE TITLE
Recover old bootloader and generate new predictions when doing a rollback

### ISSUE THREAD

**Issue by aplanas** [openSUSE/sdbootutil#77]
https://bugzilla.suse.com/show_bug.cgi?id=1222183

**Comment by lnussel** [comment]
yes. so far there is no a/b method for the bootloader
The systemd-boot change wrt loader.conf is particularly nasty as the system creating the predictions may not be aware of additional measurements required by the new bootloader.

**Comment by TobiPeterG** [comment]
Couldn't we just re-install (aka. force-update) the bootloader and then re-measure?

**Comment by TobiPeterG** [comment]
Is this solved with #150 ?

**Comment by aplanas** [comment]
I think so, yes
